version: '2'

services:

  albumlist:
    build: .
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - APP_SETTINGS=config.StagingConfig
      - MEMCACHIER_SERVERS=memcached
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=5000
    ports:
      - "5000:5000"
    links:
      - redis
      - db
      - memcached

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=config.StagingConfig
      - MEMCACHIER_SERVERS=memcached
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    links:
      - redis
      - db
      - memcached

  redis:
    image: redis

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  memcached:
    image: memcached
    ports:
      - "11211:11211"
