version: '3'

services:

  albumlist:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - APP_SETTINGS=config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - PORT=5000
    links:
      - redis
      - db
    ports:
      - "5000:5000"

  clock:
    build:
      context: .
      dockerfile: Dockerfile.clock
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    links:
      - redis
      - db

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    links:
      - redis
      - db

  redis:
    image: redis

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
